### ISSUE TITLE
Content is not provided through <nav-view>

### ISSUE THREAD

**Issue by ZachMoreno** [ionic-team/ionic-tutorial-status-fade#1]
I don't understand why in this example the side menu content for ALL nav options live within <pane> directives in index.html. Shouldn't the content populate <nav-view> with templates/... instead?

If there is a way to make this work please let me know.

**Comment by Ionitron** [comment]
Greetings @ZachMoreno!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
