### ISSUE TITLE
Android Devices

### ISSUE THREAD

**Issue by pablodenadai** [ionic-team/ionic-tutorial-status-fade#2]
Is there an option to enabled the "Status fade" effect only when running it on iOS?

See bellow issue with Android:

![Android emulator](https://f.cloud.github.com/assets/3250667/2186043/e2bacf18-97df-11e3-95d8-a85b080ae2f2.png)

**Comment by Ionitron** [comment]
Greetings @ghpabs!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
