### ISSUE TITLE
sideMenuController not available

### ISSUE THREAD

**Issue by codespore** [ionic-team/ionic-tutorial-status-fade#3]
Hey,

Just tried out the tutorial and it seems that the:

```
$scope.$watch('sideMenuController.getOpenRatio()', function(ratio) {
  ...
});
```

doesn't seem to work.

```
// The fadeBar directive
.directive('fadeBar', function($timeout, $ionicSideMenuDelegate) {
  return {
    restrict: 'E',
    template: '<div class="fade-bar"></div>',
    replace: true,
    link: function($scope, $element, $attr) {

      // Run in the next scope digest
      $timeout(function() {
        // Watch for changes to the openRatio which is a value between 0 and 1 that says how "open" the side menu is
        $scope.$watch('sideMenuController.getOpenRatio()', function(ratio) {
          console.log('Watching');
          // Set the transparency of the fade bar
          $element[0].style.opacity = Math.abs(ratio);
        });
      });
    }
  }
});
```

"sideMenuController" doesn't seem to be available via $scope. What could be the problem?

**Comment by Ionitron** [comment]
Greetings @AdrianTeh!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
